name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # 当推送标签时触发构建
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    strategy:
      matrix:
        python-version: ['3.10']
        architecture: [x64, x86]
        include:
          - architecture: x64
            python-arch: 64
          - architecture: x86
            python-arch: 32

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - name: Display Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyInstaller flask flask-cors mutagen requests PySide6

    - name: Create icon directory
      run: |
        New-Item -ItemType Directory -Path "D:/moe-n/Desktop/app" -Force
        # 复制图标文件（如果有）
        if (Test-Path "icon.ico") {
          Copy-Item "icon.ico" "D:/moe-n/Desktop/app/icon.ico" -Force
        }

    - name: Run build script
      run: python build_final.py
      env:
        PYTHONUTF8: 1

    - name: Rename artifact with architecture
      run: |
        $oldPath = "dist/MusicMetadataProcessor.exe"
        $newPath = "dist/MusicMetadataProcessor_${{ matrix.architecture }}.exe"
        if (Test-Path $oldPath) {
          Rename-Item $oldPath $newPath
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MusicMetadataProcessor_${{ matrix.architecture }}
        path: dist/MusicMetadataProcessor_${{ matrix.architecture }}.exe

    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/MusicMetadataProcessor_${{ matrix.architecture }}.exe
        draft: false
        prerelease: false
