name: Build X86

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - architecture: x64
            target: x86_64
            python_version: '3.10'

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        architecture: ${{ matrix.architecture }}

    - name: Display Python info
      run: |
        python --version
        python -c "import platform; print(f'Architecture: {platform.machine()}')"
    - name: Install dependencies with retry
      run: |
        # 设置 pip 重试和超时
        python -m pip install --upgrade pip
        pip config set global.timeout 120
        pip config set global.retries 3
        
        # 安装所有依赖，包括 flask_cors
        pip install pyinstaller==6.15.0 flask==3.1.2 mutagen==1.47.0 requests==2.32.5 flask_cors==4.0.0
        
        # 安装 PySide6
        echo "正在安装 PySide6..."
        pip install "pyside6==6.6.1" --timeout=180
        
        # 验证安装
        python -c "import flask_cors; print(f'flask_cors version: {flask_cors.__version__}')"
        python -c "import PySide6; print(f'PySide6 version: {PySide6.__version__}')"
    - name: Create icon file if missing
      run: |
        # 如果图标不存在，创建一个简单的占位图标
        if (-not (Test-Path "icon.ico")) {
          echo "图标文件不存在，创建占位图标..."
          # 这里可以添加创建简单图标的逻辑，或者跳过图标参数
          # 暂时先创建一个空文件
          echo "placeholder" > icon.ico
        }
    - name: Build executable
      run: |
        # 设置构建参数
        $buildName = "MusicMetadataProcessor_${{ matrix.target }}"
        
        # 构建命令，添加 flask_cors 相关隐藏导入
        python -m PyInstaller `
          --onefile `
          --windowed `
          --name $buildName `
          --icon=icon.ico `
          --add-data "icon.ico;." `
          --hidden-import=flask `
          --hidden-import=flask_cors `
          --hidden-import=flask_cors.core `
          --hidden-import=mutagen `
          --hidden-import=requests `
          --hidden-import=PySide6 `
          --hidden-import=PySide6.QtWidgets `
          --hidden-import=PySide6.QtCore `
          --hidden-import=PySide6.QtGui `
          --hidden-import=PySide6.QtNetwork `
          --hidden-import=werkzeug.serving `
          --hidden-import=werkzeug.middleware.dispatcher `
          --hidden-import=chardet `
          --hidden-import=charset_normalizer `
          --hidden-import=idna `
          --hidden-import=urllib3 `
          --hidden-import=certifi `
          --hidden-import=ssl `
          --hidden-import=json `
          --hidden-import=os `
          --hidden-import=sys `
          --hidden-import=threading `
          --hidden-import=time `
          --hidden-import=re `
          --hidden-import=base64 `
          --hidden-import=hashlib `
          --clean `
          --noconfirm `
          app_gui.py
        # 检查构建是否成功
        if (Test-Path "dist/$buildName.exe") {
          echo "✅ 构建成功！"
          # 重命名以包含架构信息
          Move-Item "dist/$buildName.exe" "dist/MusicMetadataProcessor_windows_${{ matrix.target }}.exe"
        } else {
          echo "❌ 构建失败，输出文件不存在"
          exit 1
        }
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.target }}-build
        path: dist/
        if-no-files-found: error

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*.exe
        body: |
          # 音乐元数据处理器
          ## 版本信息
          - 构建时间: ${{ github.event.repository.updated_at }}
          - Python版本: 3.10
          - 架构: x86_64 (64位)
          ## 使用说明
          1. 下载对应的可执行文件
          2. 双击运行即可
          ## 系统要求
          - Windows 7 或更高版本
          - .NET Framework 4.5 或更高版本
          ## 注意事项
          - 首次运行可能会被Windows Defender拦截，请选择"更多信息"->"仍要运行"
          - 确保系统中已安装必要的Visual C++运行时库
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
